---
#### Defensive Programming
# https://github.com/openshift/openshift-ansible/blob/master/docs/best_practices_guide.adoc

- name: "Set Default Cluster Facts"
  set_fact:
    openshift_persistent_volumes_def: ''
    openshift_resources_present: False
    openshift_cluster: "{{ openshift_cluster_item }}" # http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes-in-2-0
    openshift_login_url: ''
    auth_token: ''
    auth_user_pass: ''

- name: "Set Variable openshift_persistent_volumes_def Fact"
  set_fact:
    openshift_persistent_volumes_def: "{{ openshift_cluster.persistent_volumes }}"
  when:
  - openshift_cluster.persistent_volumes is defined
  - openshift_cluster.persistent_volumes|trim != ""
  - openshift_cluster.persistent_volumes|length > 0

- name: "Set OpenShift Login URL with openshift_url"
  set_fact:
    openshift_login_url: "{{ openshift_url }}"
  when: openshift_url is defined and openshift_url != ''

- name: "Set OpenShift Login URL with openshift_cluster.openshift_host_env"
  set_fact:
    openshift_login_url: "{{ openshift_cluster.openshift_host_env }}"
  when: openshift_login_url == '' and openshift_cluster.openshift_host_env is defined and openshift_cluster.openshift_host_env != ''

- name: "Set Variable openshift_resources_present Facts"
  set_fact:
    openshift_resources_present: true
  when: openshift_cluster.openshift_resources is defined and openshift_cluster.openshift_resources != "" and openshift_cluster.openshift_resources|length > 0

- name: "Set variable openshift_user when not set"
  set_fact:
    openshift_user: ''
  when: openshift_user is not defined

- name: "Set variable openshift_password when not set"
  set_fact:
    openshift_password: ''
  when: openshift_password is not defined

- name: "Set variable openshift_token when not set"
  set_fact:
    openshift_token: ''
  when: openshift_token is not defined

- name: "Check whether we will authenticate with username & password"
  set_fact:
    auth_user_pass: true
  when: openshift_user != '' and openshift_password != ''

- name: "Check whether we will authenticate with a token"
  set_fact:
    auth_token: true
  when: openshift_token != ''

- name: Fail for Missing Authentication method
  fail: msg="This role requires either openshift_token or openshift_user and openshift_password to be set"
  when: auth_token != true and auth_user_pass != true

- name: "Fail for Missing OpenShift Host Env"
  fail: msg="This role requires openshift_cluster.openshift_host_env (in the API document) or openshift_url (via CLI or host vars) to be set and non empty"
  when: 
  - openshift_resources_present|bool == True
  - openshift_login_url == ""

- name: "Log in to OpenShift Client"
  command: >
    {{ openshift.common.client_binary }} login {{ openshift_login_url }}
    --insecure-skip-tls-verify=true --username={{ openshift_user }} --password={{ openshift_password }}
  changed_when: False
  when: openshift_resources_present == true and auth_user_pass == true and auth_token != true

- name: "Add token to all openshift client comands when token is set"
  set_fact:
    openshift:
      common:
        client_binary: "{{ openshift.common.client_binary }} --token={{ openshift_token }}"
        admin_binary: "{{ openshift.common.admin_binary }} --token={{ openshift_token }}"
  when: auth_token == true

- include: create_persistent_volumes.yml
  with_items: '{{ openshift_persistent_volumes_def }}'
  loop_control:
    loop_var: persistent_volumes_item
  static: no
  when: openshift_persistent_volumes_def|trim != ''

- include: create_openshift_resources.yml
  when: openshift_resources_present|bool == True

- name: "Alert User No OpenShift Resources Were Declared"
  debug:
    msg: "There were no openshift_resources set for your openshift_cluster. This is the key data for this role, so you may want to check that you do not have typo in the request."
  when: openshift_resources_present|bool == False

