---

- name: Set Default template Facts
  set_fact:
    template: "{{ template_item }}"

- name: Fail for both template.name and template.filename set
  fail: msg="This role requires either template.name or template.filename to be set and non empty. They are mutually exclusive."
  when:
  - template.name is defined
  - template.name != ''
  - template.filename is defined
  - template.filename != ''

- name: Fail for both template.name and template.filename missing
  fail: msg="This role requires either template.name or template.filename to be set and non empty. They are mutually exclusive."
  when:
  - template.name is not defined or template.name == ''
  - template.filename is not defined or template.filename == ''

- name: "Apply {{ template.name }} Remote Template with Parameters"
  command: >
     bash -c "{{ openshift.common.client_binary }} process {{ template.name }} {{ template.parameters | oc_param_string }} | {{ openshift.common.client_binary }} apply -f - -n {{ project.name }}"
  when:
  - template.name is defined
  - template.name != ''
  - template.parameters is defined
  - template.parameters | length > 0

- name: "Apply {{ template.name }} Remote Template without Parameters"
  command: >
     bash -c "{{ openshift.common.client_binary }} process {{ template.name }} | oc apply -f - -n {{ project.name }}"
  when:
  - template.name is defined
  - template.name != ''
  - template.parameters is not defined or template.parameters | length == 0

- name: "Apply {{ template.filename }} Local Template with Parameters"
  command: >
     bash -c "{{ openshift.common.client_binary }} process -f {{ template.filename }} {{ template.parameters | oc_param_string }} | {{ openshift.common.client_binary }} apply -f - -n {{ project.name }}"
  when:
  - template.filename is defined
  - template.filename != ''
  - template.parameters is defined
  - template.parameters | length > 0

- name: "Apply {{ template.filename }} Local Template without Parameters"
  command: >
     bash -c "{{ openshift.common.client_binary }} process -f {{ template.filename }} | oc apply -f - -n {{ project.name }}"
  when:
  - template.filename is defined
  - template.filename != ''
  - template.parameters is not defined or template.parameters | length == 0